package sqlite

var tables = map[string]string{
	"subnet": `CREATE TABLE IF NOT EXISTS subnet(
id INTEGER PRIMARY KEY,
network TEXT NOT NULL UNIQUE,
start TEXT NOT NULL UNIQUE,
end TEXT NOT NULL UNIQUE,
gateway TEXT UNIQUE,
dns_server TEXT 
)`,
	"lease": `CREATE TABLE IF NOT EXISTS lease(
id INTEGER PRIMARY KEY AUTOINCREMENT,
mac_address TEXT NOT NULL,
ip_address TEXT NOT NULL UNIQUE,
subnet_id INTEGER NOT NULL,
UNIQUE(mac_address, subnet_id),
FOREIGN KEY(subnet_id) REFERENCES subnet(id) ON DELETE RESTRICT
)`,
	"host": `CREATE TABLE IF NOT EXISTS host(
id INTEGER PRIMARY KEY AUTOINCREMENT,
uuid TEXT NOT NULL UNIQUE,
name TEXT NOT NULL UNIQUE,
lease_id INTEGER NOT NULL UNIQUE,
FOREIGN KEY(lease_id) REFERENCES lease(id) ON DELETE RESTRICT
)`,
}
